<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ABMLPaciente.aspx.cs" Inherits="Vistas.ABMLPaciente" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body style="height: 645px; margin-top: 29px">
    <form id="form1" runat="server">
        <div style="height: 57px; margin-bottom: 1px;  background-color: #b71c1c">
            <br />
            <asp:Label ID="Label1" runat="server" ForeColor="White"  Text="    Bienvenido    " style="margin-left: 21px" Width="84px"></asp:Label>
            <asp:Label ID="lbl_Usuario" runat="server" BorderColor="White" ForeColor="White" Text="USUARIO"></asp:Label>
            <br />
        <div style="border-style: none; height: 757px; ">
            <br />
            <br />
            <br />
            <asp:Button ID="Button2" runat="server" Text="Agregar paciente" Width="148px" BackColor="#0066FF" ForeColor="White" style="margin-left: 56px" OnClick="Button2_Click" />
            <asp:Button ID="Button3" runat="server" BackColor="#0066FF" ForeColor="White" style="margin-left: 48px" Text="Limpiar filtro" Width="164px" OnClick="Button3_Click" />
            <asp:DropDownList ID="ddlFiltroPacientes" runat="server" BackColor="#0066FF" ForeColor="White" Height="18px" style="margin-left: 108px" Width="146px" >
                <asp:ListItem Value="0">Buscar por: DNI</asp:ListItem>
                <asp:ListItem Value="1">Buscar por: Nombre</asp:ListItem>
                <asp:ListItem Value="2">Buscar por: Apellido</asp:ListItem>
                <asp:ListItem Value="3">Buscar por: Nacionalidad</asp:ListItem>
                <asp:ListItem></asp:ListItem>
            </asp:DropDownList>
            <asp:DropDownList ID="ddlOrdenarPacientes" runat="server" BackColor="#0066FF" ForeColor="White" Height="18px" style="margin-left: 108px" Width="146px" >
                <asp:ListItem Value="0">Ordenar por: DNI</asp:ListItem>
                <asp:ListItem Value="1">Ordenar por: Nombre</asp:ListItem>
                <asp:ListItem Value="2">Ordenar por: Apellido</asp:ListItem>
                <asp:ListItem Value="3">Ordenar por: Nacionalidad</asp:ListItem>
            </asp:DropDownList>
            <asp:TextBox ID="txtboxBuscar" runat="server" style="margin-left: 320px" Width="425px"></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" style="margin-left: 1223px" Text="Buscar" Width="167px" BackColor="#B71C1C" ForeColor="White" OnClick="Button1_Click" />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <asp:Label ID="lblMensaje" runat="server"></asp:Label>
            <br />
            <br />
            <asp:GridView ID="gvPacientes" runat="server" Height="300px" Width="1094px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" OnRowCancelingEdit="gvPacientes_RowCancelingEdit" OnRowEditing="gvPacientes_RowEditing" OnRowUpdating="gvPacientes_RowUpdating" OnRowDeleting="gvPacientes_RowDeleting" OnPageIndexChanging="gvPacientes_PageIndexChanging"  DataKeyNames="DNI_Paciente, Id_Provincia, Id_Localidad" OnSelectedIndexChanged="gvPacientes_SelectedIndexChanged" >
                <AlternatingRowStyle BackColor="White" ForeColor="#284775"/>
                <Columns>
                    <asp:TemplateField HeaderText="DNI">
                        <EditItemTemplate>
                            <asp:Label ID="lblDniEdit" runat="server" Text='<%# Eval("DNI_Paciente") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_DNI" runat="server" Text='<%# Bind("DNI_Paciente") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt1" runat="server" Text='<%# Bind("nombre_paciente") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revNombre" runat="server" ControlToValidate="txt1" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$">Solo se permiten letras</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Nom" runat="server" Text='<%# Bind("nombre_paciente") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Apellido">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt2" runat="server" BorderStyle="None" Text='<%# Bind("apellido_paciente") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revApellido" runat="server" ControlToValidate="txt2" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$">Solo se permiten letras</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Apell" runat="server" Text='<%# Bind("apellido_paciente") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Sexo">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt3" runat="server" Text='<%# Bind("sexo") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revSexo" runat="server" ControlToValidate="txt3" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[MmFf]$">M o F solamente</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Sexo" runat="server" Text='<%# Bind("sexo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nacionalidad">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt7" runat="server" Text='<%# Bind("nacionalidad") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revNacionalidad" runat="server" ControlToValidate="txt7" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[a-zA-Z]+$">Solo letras</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Nacionalidad" runat="server" Text='<%# Bind("nacionalidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Fecha De Nacimiento">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Birthdate" runat="server" Text='<%# Bind("fecha_nacimiento","{0:d}") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revNacimiento" runat="server" ControlToValidate="txt_eit_Birthdate" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[0-2])/[0-9]{4}$">Solo Fechas Validas</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Birthdate" runat="server" Text='<%# Bind("fecha_nacimiento","{0:d}") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Direccion">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt5" runat="server" Text='<%# Bind("direccion") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revDireccion" runat="server" ControlToValidate="txt5" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\s\.]+ \d{1,5}$">Direccion no valida</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Dir" runat="server" Text='<%# Bind("direccion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Correo Electronico">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt4" runat="server" Text='<%# Bind("correo_electronico") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revEmail" runat="server" ControlToValidate="txt4" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[^@\s]+@[^@\s]+.[^@\s]+$">Solo se permiten formato email</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Correo" runat="server" Text='<%# Bind("correo_electronico") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Telefono">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt6" runat="server" Text='<%# Bind("telefono") %>'></asp:TextBox>
                            <asp:RegularExpressionValidator ID="revTelefono" runat="server" ControlToValidate="txt6" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^\d+$">Solo se permiten numeros</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Tel" runat="server" Text='<%# Bind("telefono") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Localidad">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlLocalidadEdit" runat="server" AutoPostBack="True" Height="16px" Width="311px">
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Localidad" runat="server" Text='<%# Bind("Nombre_Localidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Provincia">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlProvinciaEdit" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlProvinciaEdit_SelectedIndexChanged" Width="145px">
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Provincia" runat="server" Text='<%# Bind("Nombre_Provincia") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Estado">
                        <ItemTemplate>
                            <asp:Label ID="lb_it_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <br />
            <br />
            <br />
            <asp:HyperLink ID="hpInicioAdmin" runat="server" NavigateUrl="~/IniciadoAdmin.aspx">Volver al Inicio de Administrador</asp:HyperLink>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
    </form>
</body>
</html>
