<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ABMLMedicos.aspx.cs" Inherits="Vistas.ABMLMedicos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form2" runat="server">
        <div style="height: 57px; margin-bottom: 1px;  background-color: #b71c1c">
            <br />
            <asp:Label ID="Label1" runat="server" ForeColor="White"  Text="    Bienvenido    " style="margin-left: 21px" Width="84px"></asp:Label>
            <asp:Label ID="lbl" runat="server" BorderColor="White" ForeColor="White" Text="USUARIO"></asp:Label>
            <br />
        <div style="border-style: none; height: 757px; ">
            <br />
            <br />
            <br />
            <asp:Button ID="Button2" runat="server" Text="Agregar Medico" Width="148px" BackColor="#0066FF" ForeColor="White" style="margin-left: 56px" OnClick="Button2_Click" />
            <asp:Button ID="Button3" runat="server" BackColor="#0066FF" ForeColor="White" style="margin-left: 48px" Text="Limpiar filtro" Width="164px" OnClick="Button3_Click" />
            <asp:DropDownList ID="ddlFiltroMedicos" runat="server" BackColor="#0066FF" ForeColor="White" Height="18px" style="margin-left: 108px" Width="146px" >
                <asp:ListItem Value="0">Buscar por: Legajo</asp:ListItem>
                <asp:ListItem Value="1">Buscar por: Nombre</asp:ListItem>
                <asp:ListItem Value="2">Buscar por: Apellido</asp:ListItem>
                <asp:ListItem Value="3">Buscar por: Especialidad</asp:ListItem>
                <asp:ListItem></asp:ListItem>
            </asp:DropDownList>
            <asp:DropDownList ID="ddlOrdenarMedicos" runat="server" BackColor="#0066FF" ForeColor="White" Height="18px" style="margin-left: 108px" Width="146px" >
                <asp:ListItem Value="0">Ordenar por: Legajo</asp:ListItem>
                <asp:ListItem Value="1">Ordenar por: Nombre</asp:ListItem>
                <asp:ListItem Value="2">Ordenar por: Apellido</asp:ListItem>
                <asp:ListItem Value="3">Ordenar por: Especialidad</asp:ListItem>
            </asp:DropDownList>
            <asp:TextBox ID="txtboxBuscar" runat="server" style="margin-left: 258px" Width="425px" ></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" style="margin-left: 1223px" Text="Buscar" Width="167px" BackColor="#B71C1C" ForeColor="White" OnClick="Button1_Click" />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <asp:GridView ID="gvMedicos" runat="server" Height="300px" Width="1094px" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" style="margin-top: 1px" OnSelectedIndexChanged="gvMedicos_SelectedIndexChanged" OnRowDeleting="gvMedicos_RowDeleting" OnRowCancelingEdit="gvMedicos_RowCancelingEdit" OnRowEditing="gvMedicos_RowEditing" OnRowUpdating="gvMedicos_RowUpdating" OnPageIndexChanging="gvMedicos_PageIndexChanging" DataKeyNames="Legajo_Medico,Id_Provincia,Id_Localidad" OnSelectedIndexChanging="gvMedicos_SelectedIndexChanging">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
<Columns>
    <asp:TemplateField HeaderText="Legajo">
        <ItemTemplate>
            <asp:Label ID="lb_it_Leg" runat="server" Text='<%# Bind("Legajo_Medico") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Nombre">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Nombre" runat="server" Text='<%# Bind("Nombre_Medico") %>' AutoPostBack="True"></asp:TextBox>
            <asp:RegularExpressionValidator ID="revNombre" runat="server" ControlToValidate="txt_eit_Nombre" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$">Solo se permiten letras</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Nom" runat="server" Text='<%# Bind("Nombre_Medico") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Apellido">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Apellido" runat="server" Text='<%# Bind("Apellido_Medico") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revApellido" runat="server" ControlToValidate="txt_eit_Apellido" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$">Solo se permiten letras</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Apell" runat="server" Text='<%# Bind("Apellido_Medico") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Correo Electronico">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Correo" runat="server" Text='<%# Bind("Correo") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revEmail" runat="server" ControlToValidate="txt_eit_Correo" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[^@\s]+@[^@\s]+.[^@\s]+$">Solo se permiten formato email</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Correo" runat="server" Text='<%# Bind("Correo") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Telefono">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Telefono" runat="server" Text='<%# Bind("Telefono_Medico") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revTelefono" runat="server" ControlToValidate="txt_eit_Telefono" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^\d+$">Solo se permiten numeros</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Tel" runat="server" Text='<%# Bind("Telefono_Medico") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Especialidad">
        <EditItemTemplate>
            <asp:DropDownList ID="ddlEspecialidadEdit" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlEspecialidadEdit_SelectedIndexChanged" Width="145px">
            </asp:DropDownList>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Especialidad" runat="server" Text='<%# Bind("Especialidad") %>'></asp:Label>
            <br />
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Dias disponible">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Dias_dis" runat="server" Text='<%# Bind("Dia_Habil","{0:d}") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revDias" runat="server" ControlToValidate="txt_eit_Dias_dis" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[A-Za-zÁÉÍÓÚáéíóúÑñ]+(?:\s*,\s*[A-Za-zÁÉÍÓÚáéíóúÑñ]+)*$">Solo se permiten letras</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Dias_dis" runat="server" Text='<%# Bind("Dia_Habil","{0:d}") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Horario de Atencion">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Horario" runat="server" Text='<%# Bind("Horario_Atencion") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revHorario" runat="server" ControlToValidate="txt_eit_Horario" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^(?:[01]\d|2[0-3]):[0-5]\d\s*-\s*(?:[01]\d|2[0-3]):[0-5]\d$">Solo horarios </asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Horario" runat="server" Text='<%# Bind("Horario_Atencion") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="DNI">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_DNI" runat="server" Text='<%# Bind("DNI_Medico") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revDNI" runat="server" ControlToValidate="txt_eit_DNI" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^\d{8}$">Solo se permiten DNI valido</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lbl_it_DNI_Medico" runat="server" Text='<%# Bind("DNI_Medico") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Sexo">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Sexo" runat="server" Text='<%# Bind("Sexo") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revSexo" runat="server" ControlToValidate="txt_eit_Sexo" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[MmFf]$">M o F solamente</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lbl_it_Sexo" runat="server" Text='<%# Bind("Sexo") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Nacionalidad">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Nacionalidad" runat="server" Text='<%# Bind("Nacionalidad_Med") %>' Width="128px"></asp:TextBox>
            <asp:RegularExpressionValidator ID="revNacionalidad" runat="server" ControlToValidate="txt_eit_Nacionalidad" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[a-zA-Z]+$">Solo letras</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lbl_it_Nacionalidad_Med" runat="server" Text='<%# Bind("Nacionalidad_Med") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Nacimiento">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Birthdate" runat="server" Text='<%# Bind("Birthdate","{0:d}") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revNacimiento" runat="server" ControlToValidate="txt_eit_Birthdate" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[0-2])/[0-9]{4}$">Solo Fechas Validas</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lbl_it_Birthdate" runat="server" Text='<%# Bind("Birthdate","{0:d}") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Direccion">
        <EditItemTemplate>
            <asp:TextBox ID="txt_eit_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:TextBox>
            <asp:RegularExpressionValidator ID="revDireccion" runat="server" ControlToValidate="txt_eit_Direccion" ErrorMessage="RegularExpressionValidator" ForeColor="Red" ValidationExpression="^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\s\.]+ \d{1,5}$">Direccion no valida</asp:RegularExpressionValidator>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lbl_it_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Provincia">
        <EditItemTemplate>
            <asp:DropDownList ID="ddlProvinciaEdit" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlProvinciaEdit_SelectedIndexChanged" Width="145px">
            </asp:DropDownList>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Prov" runat="server" Text='<%# Bind("Nombre_Provincia") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Localidad">
        <EditItemTemplate>
            <asp:DropDownList ID="ddlLocalidadEdit" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlProvinciaEdit_SelectedIndexChanged" Width="145px">
            </asp:DropDownList>
        </EditItemTemplate>
        <ItemTemplate>
            <asp:Label ID="lb_it_Loc" runat="server" Text='<%# Bind("Nombre_Localidad") %>'></asp:Label>
        </ItemTemplate>
    </asp:TemplateField>
</Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <br />
            <br />
            <br />
            <br />
            <asp:HyperLink ID="hpInicioAdmin" runat="server" NavigateUrl="~/IniciadoAdmin.aspx">Volver al Inicio de Administrador</asp:HyperLink>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
    </form>
    
</body>
</html>